import { Canvas, useFrame, useThree } from '@react-three/fiber';
import { Sparkles, Stars } from '@react-three/drei';
import { useRef } from 'react';
import type { Group, Mesh } from 'three';

export type ArenaTarget = { x: number; z: number; kind: 'quiz' | 'enemy'; label: string };
interface Arena3DProps { playerPosition: { x: number; z: number }; target: ArenaTarget | null; bossActive: boolean; bossHp: number; onReachTarget: () => void; }

function Explorer({ position }: { position: { x: number; z: number } }) {
  const group = useRef<Group>(null);
  useFrame((state) => { if (group.current) group.current.rotation.y = Math.sin(state.clock.elapsedTime * 3) * 0.08; });
  return <group ref={group} position={[position.x, .75, position.z]}><mesh castShadow><capsuleGeometry args={[.38, .82, 6, 12]}/><meshStandardMaterial color="#27cfdb" roughness={.35}/></mesh><mesh position={[0,.72,.02]} castShadow><sphereGeometry args={[.47,24,24]}/><meshStandardMaterial color="#ffd3ae"/></mesh><mesh position={[0,1.1,.04]}><boxGeometry args={[.86,.18,.7]}/><meshStandardMaterial color="#5835bb"/></mesh><mesh position={[-.16,.76,.42]}><sphereGeometry args={[.055,12,12]}/><meshStandardMaterial color="#14213d"/></mesh><mesh position={[.16,.76,.42]}><sphereGeometry args={[.055,12,12]}/><meshStandardMaterial color="#14213d"/></mesh></group>;
}

function Enemy({ position, boss = false }: { position: [number,number,number]; boss?: boolean }) {
  const group = useRef<Group>(null); useFrame((state) => { if (group.current) { group.current.position.y = position[1] + Math.sin(state.clock.elapsedTime * 2) * .12; group.current.rotation.y += boss ? .012 : .02; } });
  return <group ref={group} position={position}><mesh castShadow><sphereGeometry args={[boss ? .95 : .56, 20,20]}/><meshStandardMaterial color={boss ? '#ef426f' : '#ff8739'} emissive={boss ? '#5a1024' : '#3f1200'} emissiveIntensity={.6}/></mesh><mesh position={[0,boss ? 1.04 :.64,0]}><coneGeometry args={[boss ? .36 :.22,boss ? .92 :.5,5]}/><meshStandardMaterial color="#ffd43b"/></mesh><mesh position={[-.18,0,.52]}><sphereGeometry args={[.08,12,12]}/><meshStandardMaterial color="#fff4bd" emissive="#fff4bd" emissiveIntensity={1}/></mesh><mesh position={[.18,0,.52]}><sphereGeometry args={[.08,12,12]}/><meshStandardMaterial color="#fff4bd" emissive="#fff4bd" emissiveIntensity={1}/></mesh></group>;
}

function TargetMarker({ target }: { target: ArenaTarget }) { const ref=useRef<Mesh>(null); useFrame((state)=>{ if(ref.current){ref.current.rotation.y+=.03;ref.current.position.y=.8+Math.sin(state.clock.elapsedTime*3)*.12;} }); return target.kind === 'enemy' ? <Enemy position={[target.x,.62,target.z]}/> : <group position={[target.x,0,target.z]}><mesh ref={ref} position={[0,.8,0]}><octahedronGeometry args={[.45]}/><meshStandardMaterial color="#56f5df" emissive="#56f5df" emissiveIntensity={2}/></mesh><Sparkles count={20} scale={1.7} size={3} speed={.4} color="#fff28a"/></group>; }

function CameraFollow({ position }: { position: {x:number;z:number} }) { const {camera}=useThree(); useFrame(()=>{camera.position.lerp({x:position.x,y:13,z:position.z+10} as never,.08);camera.lookAt(position.x,0,position.z-1.5);}); return null; }
function Scene({ playerPosition,target,bossActive,bossHp,onReachTarget }: Arena3DProps) { const reached=useRef(false); useFrame(()=>{ if(!target){reached.current=false;return;} const d=Math.hypot(playerPosition.x-target.x,playerPosition.z-target.z); if(d<1.05&&!reached.current&&target.kind==='quiz'){reached.current=true;onReachTarget();} if(d>1.4)reached.current=false; }); return <><ambientLight intensity={1.2}/><directionalLight position={[5,10,5]} intensity={2.5} castShadow/><pointLight position={[-4,4,-4]} color="#34d4e8" intensity={16} distance={11}/><Stars radius={34} depth={20} count={500} factor={2} fade/><mesh receiveShadow rotation={[-Math.PI/2,0,0]}><planeGeometry args={[22,22]}/><meshStandardMaterial color="#205c4a" roughness={.92}/></mesh><mesh receiveShadow rotation={[-Math.PI/2,0,0]} position={[0,.02,0]}><circleGeometry args={[10,64]}/><meshStandardMaterial color="#3f9b72" roughness={.85}/></mesh>{[[-7,-3],[-5,5],[3,6],[7,2],[-1,-7]].map(([x,z],i)=><mesh key={i} position={[x,.55,z]} castShadow><dodecahedronGeometry args={[.7,0]}/><meshStandardMaterial color="#7854bd"/></mesh>)}{target&&<TargetMarker target={target}/>} {bossActive&&bossHp>0&&<Enemy boss position={[5.5,.9,-4.8]}/>}<Explorer position={playerPosition}/><mesh position={[playerPosition.x,.07,playerPosition.z]} rotation={[-Math.PI/2,0,0]}><ringGeometry args={[.58,.72,28]}/><meshBasicMaterial color="#ffffff" transparent opacity={.85}/></mesh><CameraFollow position={playerPosition}/></>; }
export function Arena3D(props:Arena3DProps){ return <Canvas shadows camera={{position:[0,13,10],fov:50}} dpr={[1,1.5]} className="h-full w-full"><Scene {...props}/></Canvas>; }
