import { useEffect, useState } from 'react';
import { ArrowDown, ArrowLeft, ArrowRight, ArrowUp, CircleHelp, Heart, Shield, Sparkles, Swords, X } from 'lucide-react';
import { PlayerProfile } from '../types';
import { Arena3D, ArenaTarget } from './Arena3D';

interface BattleScreenProps { territoryId: string; profile: PlayerProfile; onWin: (territory: string, xp: number, coins: number) => void; onLeave: () => void; }
type Challenge = { topic: string; name: string; prompt: string; options: string[]; answer: string };

const stories: Record<string, { title: string; portal: string; theme: string; questions: Challenge[] }> = {
  brasil: { title: 'Ruínas do Brasil', portal: 'Portal das Águas', theme: 'Floresta', questions: [
    { name: 'Cristal do Rio', topic: 'Águas da floresta', prompt: 'Por que os rios da Amazônia são importantes?', options: ['Somente para barcos', 'Ajudam a manter a vida, o clima e comunidades', 'Não têm relação com a floresta', 'Servem apenas como fronteira'], answer: 'Ajudam a manter a vida, o clima e comunidades' },
    { name: 'Semente da Vida', topic: 'Biodiversidade', prompt: 'O que significa biodiversidade?', options: ['Ter apenas uma espécie', 'A variedade de seres vivos de um lugar', 'Construir mais cidades', 'Cortar árvores antigas'], answer: 'A variedade de seres vivos de um lugar' },
    { name: 'Totem Verde', topic: 'Preservação', prompt: 'Qual escolha protege melhor uma floresta?', options: ['Descartar lixo nos rios', 'Queimar áreas para abrir espaço', 'Respeitar áreas protegidas e usar recursos com cuidado', 'Retirar animais do habitat'], answer: 'Respeitar áreas protegidas e usar recursos com cuidado' },
    { name: 'Olhar Atento', topic: 'Investigação', prompt: 'Qual atitude ajuda a aprender sobre a natureza?', options: ['Observar e buscar informações confiáveis', 'Acreditar no primeiro boato', 'Ignorar evidências', 'Escolher sem pensar'], answer: 'Observar e buscar informações confiáveis' },
    { name: 'Guardião do Rio', topic: 'Sustentabilidade', prompt: 'O que ajuda a proteger a água?', options: ['Evitar poluir rios e nascentes', 'Jogar resíduos na rua', 'Desperdiçar água potável', 'Ignorar vazamentos'], answer: 'Evitar poluir rios e nascentes' },
  ] },
  mexico: { title: 'Vale do México', portal: 'Portal do Sol', theme: 'Templos', questions: [] },
  egito: { title: 'Areias do Egito', portal: 'Portal do Nilo', theme: 'Pirâmides', questions: [] },
  japao: { title: 'Ilhas do Japão', portal: 'Portal dos Ventos', theme: 'Ilhas', questions: [] },
  andes: { title: 'Cordilheira dos Andes', portal: 'Portal das Montanhas', theme: 'Montanhas', questions: [] },
  oceano: { title: 'Recifes do Pacífico', portal: 'Portal das Marés', theme: 'Oceano', questions: [] },
  savana: { title: 'Savanas da África', portal: 'Portal dos Baobás', theme: 'Savana', questions: [] },
  espaco: { title: 'Estação Estelar', portal: 'Portal das Constelações', theme: 'Espaço', questions: [] },
};
const mathChallenges = [
  { prompt: '12 + 8 = ?', options: ['18', '20', '22', '24'], answer: '20' }, { prompt: '35 − 9 = ?', options: ['24', '25', '26', '27'], answer: '26' }, { prompt: '6 × 7 = ?', options: ['36', '40', '42', '48'], answer: '42' }, { prompt: '48 ÷ 6 = ?', options: ['6', '7', '8', '9'], answer: '8' },
];
const fallbackQuestions = [
  { name: 'Mapa do Lugar', topic: 'Geografia', prompt: 'Para que mapas são úteis?', options: ['Localizar lugares e compreender espaços', 'Mudar o clima', 'Criar animais novos', 'Substituir viagens'], answer: 'Localizar lugares e compreender espaços' },
  { name: 'Memória Viva', topic: 'Cultura', prompt: 'Por que preservar a história de um lugar é importante?', options: ['Ajuda a compreender pessoas e culturas', 'Só serve para decorar livros', 'Não tem relação com o presente', 'Impede aprendizados'], answer: 'Ajuda a compreender pessoas e culturas' },
  { name: 'Vida em Equilíbrio', topic: 'Ciências', prompt: 'O que pode ocorrer quando uma espécie desaparece?', options: ['O equilíbrio do ambiente pode ser afetado', 'Nada muda', 'Todas as plantas crescem', 'Os rios desaparecem'], answer: 'O equilíbrio do ambiente pode ser afetado' },
  { name: 'Escolha Consciente', topic: 'Sustentabilidade', prompt: 'O que é usar um recurso com responsabilidade?', options: ['Evitar desperdícios e pensar no futuro', 'Usar sem limites', 'Descartar quando quiser', 'Impedir todo uso'], answer: 'Evitar desperdícios e pensar no futuro' },
  { name: 'Cuidado Coletivo', topic: 'Cidadania', prompt: 'Qual escolha cuida de um espaço coletivo?', options: ['Respeitar regras e colaborar', 'Danificar o que é de todos', 'Deixar lixo', 'Ignorar ajuda'], answer: 'Respeitar regras e colaborar' },
];
const checkpoints: ArenaTarget[] = [
  { x: -5.5, z: 4, kind: 'quiz', label: 'Cristal do Saber' }, { x: -2.2, z: 2.6, kind: 'enemy', label: 'Sentinela da Selva' },
  { x: 1.5, z: 3.8, kind: 'quiz', label: 'Totem do Conhecimento' }, { x: 4.8, z: 1.3, kind: 'enemy', label: 'Caçador Sombrio' },
  { x: 2.6, z: -1.9, kind: 'quiz', label: 'Cristal Ancestral' }, { x: -1.4, z: -.8, kind: 'enemy', label: 'Guardião Menor' },
  { x: -5.3, z: -2.2, kind: 'quiz', label: 'Semente de Luz' }, { x: -3.9, z: -5.4, kind: 'enemy', label: 'Batedor da Ruína' },
  { x: .5, z: -5.5, kind: 'quiz', label: 'Chama da Sabedoria' }, { x: 4.4, z: -3.4, kind: 'enemy', label: 'Sentinela Final' },
];

export function BattleScreen({ territoryId, profile, onWin, onLeave }: BattleScreenProps) {
  const base = stories[territoryId] ?? stories.brasil;
  const questions = base.questions.length ? base.questions : fallbackQuestions;
  const storageKey = `terravox.arena3.${profile.name.trim().toLowerCase()}.${territoryId}`;
  const [saved] = useState(() => { try { return JSON.parse(localStorage.getItem(storageKey) || '{}') as { step?: number; hp?: number; enemyHp?: number; bossHp?: number; pos?: { x: number; z: number } }; } catch { return {}; } });
  const [step, setStep] = useState(saved.step ?? 0); const [hp, setHp] = useState(saved.hp ?? 100); const [enemyHp, setEnemyHp] = useState(saved.enemyHp ?? 100); const [bossHp, setBossHp] = useState(saved.bossHp ?? 100); const [pos, setPos] = useState(saved.pos ?? { x: -7.5, z: 5.5 });
  const [modal, setModal] = useState<'quiz' | 'math' | null>(null); const [won, setWon] = useState(false); const [help, setHelp] = useState(false); const [feedback, setFeedback] = useState('Explore a arena: cristais liberam perguntas e sentinelas precisam ser derrotadas.');
  const active = step < checkpoints.length ? checkpoints[step] : null; const boss = !active;
  useEffect(() => { localStorage.setItem(storageKey, JSON.stringify({ step, hp, enemyHp, bossHp, pos })); }, [storageKey, step, hp, enemyHp, bossHp, pos]);
  const move = (x: number, z: number) => setPos(current => ({ x: Math.max(-9, Math.min(9, current.x + x)), z: Math.max(-8, Math.min(8, current.z + z)) }));
  useEffect(() => { const onKey = (event: KeyboardEvent) => { const keys: Record<string, [number, number]> = { ArrowUp: [0, -.65], w: [0, -.65], ArrowDown: [0, .65], s: [0, .65], ArrowLeft: [-.65, 0], a: [-.65, 0], ArrowRight: [.65, 0], d: [.65, 0] }; const direction = keys[event.key]; if (direction && !modal && !won) { event.preventDefault(); move(direction[0], direction[1]); } }; window.addEventListener('keydown', onKey); return () => window.removeEventListener('keydown', onKey); }, [modal, won]);
  const loseEnergy = (amount: number, text: string) => { const next = Math.max(0, hp - amount); setHp(next); setFeedback(next ? text : 'Sua energia acabou. Você voltou para o último ponto seguro.'); if (!next) { setHp(100); setPos({ x: -7.5, z: 5.5 }); setStep(Math.max(0, step - 1)); setEnemyHp(100); setModal(null); } };
  const answerQuiz = (option: string) => { const question = questions[Math.floor(step / 2)]; if (option !== question.answer) { loseEnergy(15, 'Resposta incorreta. Você perdeu 15 de energia. Escolha outra resposta.'); return false; } setModal(null); setStep(value => value + 1); setFeedback('Resposta correta. Avance até o próximo desafio.'); return true; };
  const attack = () => { if (!active || active.kind !== 'enemy') return; const distance = Math.hypot(pos.x - active.x, pos.z - active.z); if (distance > 1.65) { setFeedback('Aproxime-se da sentinela para atacar.'); return; } const next = Math.max(0, enemyHp - 25); setEnemyHp(next); if (!next) { setEnemyHp(100); setStep(value => value + 1); setFeedback('Sentinela derrotada. A próxima marca foi liberada.'); } else setFeedback('Acerto! A sentinela perdeu 25 de energia.'); };
  const answerMath = (option: string) => { const question = mathChallenges[Math.min(3, Math.floor((100 - bossHp) / 25))]; if (option !== question.answer) { loseEnergy(15, 'Conta incorreta. O Guardião contra-atacou. Escolha outra resposta.'); return false; } const next = Math.max(0, bossHp - 25); setBossHp(next); setModal(null); if (!next) { localStorage.removeItem(storageKey); setWon(true); setFeedback('O Guardião foi derrotado!'); } else setFeedback('Conta correta. O Guardião perdeu 25 de energia.'); return true; };
  const currentQuestion = questions[Math.floor(step / 2)]; const math = mathChallenges[Math.min(3, Math.floor((100 - bossHp) / 25))];
  return <main className="relative h-[100dvh] overflow-hidden bg-[#061126] text-white"><header className="absolute inset-x-0 top-0 z-30 flex items-center justify-between p-3 sm:p-5"><button onClick={onLeave} className="rounded-xl border border-white/30 bg-slate-950/80 px-3 py-2 text-sm font-black"><ArrowLeft className="mr-1 inline h-4 w-4"/>Sair</button><div className="text-center"><p className="text-[10px] font-black tracking-[.28em] text-cyan-200">TERRAVOX 3D</p><h1 className="text-lg font-black sm:text-2xl">{base.title}</h1></div><div className="rounded-xl bg-slate-950/80 px-3 py-2 text-right text-xs font-bold">{profile.name}<br/><span className="text-yellow-300">Nível {profile.level}</span></div></header>
    <aside className="absolute left-3 top-20 z-30 w-40 rounded-2xl border border-white/25 bg-[#071528]/85 p-3 backdrop-blur"><p className="flex gap-1 text-xs font-black"><Heart className="h-4 w-4 text-rose-400"/> EXPLORADOR</p><div className="mt-2 h-3 overflow-hidden rounded-full bg-slate-900"><div className="h-full bg-gradient-to-r from-cyan-400 to-emerald-300 transition-all" style={{ width: `${hp}%` }}/></div><p className="mt-1 text-right text-xs font-black">{hp}/100</p>{boss && <><div className="my-2 border-t border-white/15"/><p className="text-xs font-black text-rose-200">GUARDIÃO</p><div className="mt-2 h-3 overflow-hidden rounded-full bg-slate-900"><div className="h-full bg-gradient-to-r from-rose-600 to-orange-400" style={{ width: `${bossHp}%` }}/></div></>}</aside>
    <section className="absolute inset-0"><Arena3D playerPosition={pos} target={active} bossActive={boss} bossHp={bossHp} onReachTarget={() => { if (active?.kind === 'quiz') setModal('quiz'); }}/></section>
    <div className="pointer-events-none absolute inset-x-4 bottom-4 z-20 flex justify-center"><p className="rounded-2xl border border-cyan-100/30 bg-slate-950/80 px-4 py-2 text-center text-xs font-bold backdrop-blur">{boss ? 'Guardião à vista: resolva contas para atacar.' : active?.kind === 'quiz' ? `Caminhe até ${active.label}.` : `Chegue perto de ${active?.label} e ataque.`}</p></div>
    <div className="absolute bottom-5 left-4 z-30 grid grid-cols-3 gap-1 sm:hidden"><span/><button onClick={() => move(0, -.8)} className="grid h-12 w-12 place-items-center rounded-xl border border-cyan-100/60 bg-slate-950/85 text-cyan-50 active:scale-95"><ArrowUp/></button><span/><button onClick={() => move(-.8, 0)} className="grid h-12 w-12 place-items-center rounded-xl border border-cyan-100/60 bg-slate-950/85 text-cyan-50 active:scale-95"><ArrowLeft/></button><button onClick={() => move(0, .8)} className="grid h-12 w-12 place-items-center rounded-xl border border-cyan-100/60 bg-slate-950/85 text-cyan-50 active:scale-95"><ArrowDown/></button><button onClick={() => move(.8, 0)} className="grid h-12 w-12 place-items-center rounded-xl border border-cyan-100/60 bg-slate-950/85 text-cyan-50 active:scale-95"><ArrowRight/></button></div>
    {active?.kind === 'enemy' && <button onClick={attack} className="absolute bottom-20 right-5 z-30 rounded-full border-4 border-yellow-100 bg-gradient-to-b from-yellow-300 to-orange-500 px-5 py-4 text-xs font-black text-slate-950 shadow-[0_0_25px_rgba(250,204,21,.75)]"><Swords className="mx-auto mb-1 h-5 w-5"/>ATACAR<br/>{enemyHp}/100</button>}
    {boss && <button onClick={() => setModal('math')} className="absolute bottom-20 right-5 z-30 rounded-full border-4 border-yellow-100 bg-gradient-to-b from-yellow-300 to-orange-500 px-5 py-4 text-xs font-black text-slate-950 shadow-[0_0_25px_rgba(250,204,21,.75)]"><Swords className="mx-auto mb-1 h-5 w-5"/>ATACAR<br/>COM A CONTA</button>}
    <button onClick={() => setHelp(true)} className="absolute bottom-5 right-5 z-30 grid h-12 w-12 place-items-center rounded-2xl border-2 border-cyan-100/70 bg-[#071528]/90"><CircleHelp/></button>
    {help && <div className="absolute inset-0 z-40 grid place-items-end bg-slate-950/50 p-4 backdrop-blur sm:place-items-center"><section className="w-full max-w-sm rounded-3xl bg-[#071528] p-5"><button onClick={() => setHelp(false)} className="float-right"><X/></button><p className="text-xs font-black tracking-[.18em] text-cyan-200">COMO JOGAR</p><h2 className="mt-2 text-xl font-black">Arena 3D interativa</h2><p className="mt-3 text-sm leading-relaxed text-slate-200">No celular, use as setas. No computador, use WASD ou as setas do teclado. Cristais abrem perguntas. Sentinelas exigem que você se aproxime e ataque. Ao final, matemática derruba o Guardião.</p></section></div>}
    {modal === 'quiz' && <QuestionModal eyebrow={currentQuestion.topic} title={currentQuestion.name} prompt={currentQuestion.prompt} options={currentQuestion.options} onAnswer={answerQuiz}/>} {modal === 'math' && <QuestionModal eyebrow="ATAQUE DE LÓGICA" title="Conta contra o Guardião" prompt={math.prompt} options={math.options} onAnswer={answerMath}/>} {won && <div className="absolute inset-0 z-50 grid place-items-center bg-[#071528]/75 p-5 backdrop-blur"><section className="w-full max-w-sm rounded-[2rem] bg-gradient-to-br from-emerald-500 to-cyan-700 p-8 text-center"><Sparkles className="mx-auto h-12 w-12 text-yellow-100"/><h2 className="mt-3 text-3xl font-black">Território restaurado!</h2><p className="my-4 font-medium">Você venceu os desafios e o Guardião.</p><button onClick={() => onWin(territoryId, 150, 40)} className="w-full rounded-xl bg-yellow-200 py-4 font-black text-slate-950">COLETAR +150 XP</button></section></div>}
  </main>;
}

function QuestionModal({ eyebrow, title, prompt, options, onAnswer }: { eyebrow: string; title: string; prompt: string; options: string[]; onAnswer: (option: string) => boolean }) { const [error, setError] = useState<string | null>(null); const choose = (option: string) => setError(onAnswer(option) ? null : 'Resposta incorreta. Você perdeu energia. Escolha outra alternativa.'); return <div className="absolute inset-0 z-40 grid place-items-end bg-[#071528]/80 p-3 backdrop-blur-sm sm:place-items-center"><section className="w-full max-w-xl rounded-[2rem] border-2 border-yellow-200/70 bg-[linear-gradient(135deg,#174054,#3b1b68)] p-5 text-center shadow-2xl sm:p-9"><Shield className="mx-auto h-8 w-8 text-yellow-200"/><p className="mt-2 text-xs font-black tracking-[.2em] text-yellow-200">{eyebrow}</p><h2 className="mt-2 text-xl font-black">{title}</h2><p className="my-4 text-base font-bold leading-relaxed">{prompt}</p>{error && <p className="mb-3 rounded-xl bg-rose-950/70 p-3 text-sm font-bold text-rose-100">{error}</p>}<div className="grid gap-3 sm:grid-cols-2">{options.map(option => <button key={option} onClick={() => choose(option)} className="rounded-xl border border-white/20 bg-white/10 p-3 text-left text-sm font-bold hover:border-yellow-200 hover:bg-yellow-200 hover:text-slate-950">{option}</button>)}</div></section></div>; }
